#!/bin/bash

# /etc/init.d/scripts
# Description: Script for get_stats tool
# ————————————————–
#
### BEGIN INIT INFO
# Provides: Scripts for get_stats
# Required-Start: $network $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start Python scripts to provide get_stats
### END INIT INFO
PIDDIR=/var/run/get_stats
PIDFILE=/var/run/get_stats/get_stats
DAEMONLOG=/var/log/get_stats/daemon/get_stats.log

if [ ! -d $PIDDIR ] ; then
        mkdir -p $PIDDIR
fi


case "$1" in
 start)
   if [ ! -f $PIDFILE ] ; then
                echo "Starting get_stats tool..."
                su root -c "nohup /usr/bin/python -u /root/utils/get_stats.py > $DAEMONLOG 2>&1 &"
   else
         for pid in $(cat $PIDFILE) ; do
                if ! ps --no-headers p "$pid" | grep socket-server-adam > /dev/null ; then
                        echo "Starting get_stats tool..."
                        su root -c "nohup /usr/bin/python -u /root/utils/get_stats.py > $DAEMONLOG 2>&1 &"
                else
                        echo "The get_stats tool is already running!!"
        fi
   done
  fi
  ;;
 stop)
  if [ ! -f $PIDFILE ] ; then
                echo "The get_stats tool is not running"
  else
        for pid in $(cat $PIDFILE) ; do
                if ! ps --no-headers p "$pid" | grep get_stats > /dev/null ; then
                        echo "The get_stats tool is not running"
                else
                        echo "Stopping get_stats tool..."
                        kill -9 $pid
                fi
        done
  fi
  ;;

 restart)
   $0 stop
   sleep 1
   $0 start
   ;;
 *)
   echo "usage: $0 {start|stop|restart}"  
esac

exit 0